apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    run: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      securityContext:
        fsGroup: 101
      volumes:
        - name: web-data
          emptyDir: {}
      containers:
        - name: git-sync
          image: 'registry.k8s.io/git-sync/git-sync:v4.2.3'
          imagePullPolicy: Always
          args:
            - '--repo=https://github.com/Neoop1/DevOpsEcommerceFruitsBazar.git'
            - '--branch=wwwdata'
            - '--depth=1'
            - '--period=60s'
            - '--link=html'
            - '--root=/web'
          volumeMounts:
            - name: web-data
              mountPath: /web
        - name: nginx-webserver
          image: richarvey/nginx-php-fpm
          volumeMounts:
            - name: web-data
              mountPath: /web
              readOnly: true
          env:
            - name: WEBROOT
              value: /web/html
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_DATABASE
              value: ecommerce
            - name: MARIADB_DB # Site env
              value: ecommerce
            - name: MARIADB_PORT
              value: '3306'
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
          ports:
            - name: webserver
              containerPort: 80
