apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-www-pvc
spec:
  storageClassName: ""
  volumeName: nfs-www
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G