apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-www
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - soft
    - nfsvers=4
  nfs:
    path: /nfs_srv/kube/ecommerce-website.com/
    server: 192.168.7.103
    readOnly: false


