apiVersion: v1
kind: Service
metadata:
  labels:
    name: nfs-server
  name: nfs-server
spec:
  ports:
    - name: nfs-server
      port: 2049
      targetPort: 2049
  selector:
    app: nfs-server
  type: NodePort
