apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - image: neoop1/nfsserver
        securityContext:
           privileged: true
        imagePullPolicy: Always
        name: nfs-server
        ports:
        - name: nfs-server
          containerPort: 2049

        env:
          - name: NFS_SERVER_ALLOWED_CLIENTS
            value: 172.16.0.0/12


     


