apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: bitnami/mariadb:11.2.4
          name: mariadb
          env:
          - name: MARIADB_HOST
            value: mysqlserver

          - name: MARIADB_DATABASE
            value: ecommerce

          - name:  MARIADB_PORT
            value: "3306"

          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-username
                
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-password
          
          ports:
            - name: mariadb
              containerPort: 3306
              
          volumeMounts:
            - name: nfs-sql-vol
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: nfs-sql-vol
          persistentVolumeClaim:
            claimName: nfs-sql-pvc
